; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32s3box]
platform = espressif32
board = esp32s3box
framework = arduino
monitor_speed = 115200
board_upload.flash_size = 8MB
board_build.partitions = partitions/myscreen_8MB.csv
board_build.filesystem = littlefs
build_flags = 
	-D BOARD_HAS_PSRAM
	-D LV_CONF_INCLUDE_SIMPLE
	-D LV_LVGL_H_INCLUDE_SIMPLE
	-D CONFIG_MBEDTLS_DYNAMIC_BUFFER=1
	-D CONFIG_MBEDTLS_SSL_IN_CONTENT_LEN=8192
	-D CONFIG_MBEDTLS_SSL_OUT_CONTENT_LEN=4096
	-D CONFIG_MBEDTLS_EXTERNAL_MEM_ALLOC=1
	-I lib
	-I include
extra_scripts = extra_script.py
board_build.arduino.memory_type = qio_opi
board_build.f_flash = 80000000L
board_build.flash_mode = qio
build_src_filter =
	+<*>
	-<src/fonts/comment_emoji_24.c>
lib_deps = 
	lvgl/lvgl@8.3.8
	bblanchon/ArduinoJson@6.21.5
	https://github.com/webmproject/libwebp.git#v1.4.0
	bitbank2/JPEGDEC@1.8.2
