// Auto-generated by tools/gen_comment_bubble_deco.py
#pragma once
#include <lvgl.h>

#define COMMENT_STYLE_ICON_SIZE 40
#define COMMENT_STYLE_ICON_LOVE_W 56
#define COMMENT_STYLE_ICON_LOVE_H 40

extern const lv_img_dsc_t comment_style_icon_dialogue;
extern const lv_img_dsc_t comment_style_icon_festive;
extern const lv_img_dsc_t comment_style_icon_warning;
extern const lv_img_dsc_t comment_style_icon_love;
