// Auto-generated by tools/gen_comment_emoji_images.py
#pragma once
#include <lvgl.h>

#define COMMENT_EMOJI_IMG_SIZE 28

extern const lv_img_dsc_t comment_emoji_sparkles;
extern const lv_img_dsc_t comment_emoji_heart;
extern const lv_img_dsc_t comment_emoji_grin;
extern const lv_img_dsc_t comment_emoji_cool;
extern const lv_img_dsc_t comment_emoji_thumbsup;
extern const lv_img_dsc_t comment_emoji_muscle;
