// Auto-generated by tools/gen_google_weather_icons.py
#pragma once
#include <lvgl.h>

#define WEATHER_ICON_SIZE 72

extern const lv_img_dsc_t weather_img_clear_day;
extern const lv_img_dsc_t weather_img_clear_night;
extern const lv_img_dsc_t weather_img_partly_cloudy_day;
extern const lv_img_dsc_t weather_img_partly_cloudy_night;
extern const lv_img_dsc_t weather_img_cloudy_day;
extern const lv_img_dsc_t weather_img_cloudy_night;
extern const lv_img_dsc_t weather_img_rain_day;
extern const lv_img_dsc_t weather_img_rain_night;
extern const lv_img_dsc_t weather_img_snow_day;
extern const lv_img_dsc_t weather_img_snow_night;
extern const lv_img_dsc_t weather_img_sleet_day;
extern const lv_img_dsc_t weather_img_sleet_night;
extern const lv_img_dsc_t weather_img_hail_day;
extern const lv_img_dsc_t weather_img_hail_night;
extern const lv_img_dsc_t weather_img_thunder_day;
extern const lv_img_dsc_t weather_img_thunder_night;
extern const lv_img_dsc_t weather_img_thunderstorm_day;
extern const lv_img_dsc_t weather_img_thunderstorm_night;
extern const lv_img_dsc_t weather_img_fog_day;
extern const lv_img_dsc_t weather_img_fog_night;
extern const lv_img_dsc_t weather_img_haze_day;
extern const lv_img_dsc_t weather_img_haze_night;
extern const lv_img_dsc_t weather_img_wind_day;
extern const lv_img_dsc_t weather_img_wind_night;
extern const lv_img_dsc_t weather_img_unknown;
