#!/usr/bin/env python3
"""Rasterize preset comment emojis to LVGL RGB565 images (full color).

Uses Segoe UI Emoji on Windows. Run:
  pip install Pillow
  python tools/gen_comment_emoji_images.py
  pio run
"""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT_C = ROOT / "src" / "comment_emoji_images.c"
OUT_H = ROOT / "include" / "comment_emoji_images.h"
WIN_FONT = Path(r"C:\WINDOWS\Fonts\seguiemj.ttf")

SIZE = 28
CHROMA = 0x07E0
ALPHA_THRESH = 128
FONT_PX = 22

# (C symbol suffix, character)
EMOJIS: list[tuple[str, str]] = [
    ("sparkles", "\u2728"),
    ("heart", "\u2764"),
    ("grin", "\U0001f601"),
    ("cool", "\U0001f60e"),
    ("thumbsup", "\U0001f44d"),
    ("muscle", "\U0001f4aa"),
]


def rgb565(r: int, g: int, b: int) -> int:
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def find_font() -> Path:
    if WIN_FONT.is_file():
        return WIN_FONT
    for p in (ROOT / "data" / "fonts").glob("*.ttf"):
        if "emoji" in p.name.lower() or "segui" in p.name.lower():
            return p
    raise SystemExit("No emoji TTF found (need Segoe UI Emoji or data/fonts/*.ttf)")


def render_emoji(font_path: Path, char: str) -> list[int]:
    from PIL import Image, ImageDraw, ImageFont

    font = ImageFont.truetype(str(font_path), FONT_PX)
    im = Image.new("RGBA", (SIZE, SIZE), (0, 0, 0, 0))
    draw = ImageDraw.Draw(im)
    bbox = draw.textbbox((0, 0), char, font=font)
    tw = bbox[2] - bbox[0]
    th = bbox[3] - bbox[1]
    x = (SIZE - tw) // 2 - bbox[0]
    y = (SIZE - th) // 2 - bbox[1]
    draw.text((x, y), char, font=font, embedded_color=True)

    buf: list[int] = []
    for py in range(SIZE):
        for px in range(SIZE):
            r, g, b, a = im.getpixel((px, py))
            if a < ALPHA_THRESH:
                buf.append(CHROMA)
            else:
                buf.append(rgb565(r, g, b))
    return buf


def c_array(name: str, buf: list[int]) -> str:
    lines = [f"static const uint8_t comment_emoji_{name}_map[] = {{"]
    for y in range(SIZE):
        row = buf[y * SIZE : (y + 1) * SIZE]
        bytes_out: list[str] = []
        for pixel in row:
            bytes_out.append(f"0x{pixel & 0xFF:02X}")
            bytes_out.append(f"0x{(pixel >> 8) & 0xFF:02X}")
        lines.append("    " + ", ".join(bytes_out) + ",")
    lines.append("};")
    return "\n".join(lines)


def main() -> None:
    try:
        from PIL import Image  # noqa: F401
    except ImportError as exc:
        raise SystemExit("pip install Pillow") from exc

    font_path = find_font()
    print(f"Generating {SIZE}x{SIZE} color emojis from {font_path.name}...")

    c_parts = [
        "// Auto-generated by tools/gen_comment_emoji_images.py",
        "#include <lvgl.h>",
        "",
    ]
    h_parts = [
        "// Auto-generated by tools/gen_comment_emoji_images.py",
        "#pragma once",
        "#include <lvgl.h>",
        "",
        f"#define COMMENT_EMOJI_IMG_SIZE {SIZE}",
        "",
    ]

    for name, char in EMOJIS:
        buf = render_emoji(font_path, char)
        c_parts.append(c_array(name, buf))
        c_parts.append(
            f"""
const lv_img_dsc_t comment_emoji_{name} = {{
    .header.cf = LV_IMG_CF_TRUE_COLOR_CHROMA_KEYED,
    .header.always_zero = 0,
    .header.reserved = 0,
    .header.w = {SIZE},
    .header.h = {SIZE},
    .data_size = sizeof(comment_emoji_{name}_map),
    .data = comment_emoji_{name}_map,
}};
"""
        )
        h_parts.append(f"extern const lv_img_dsc_t comment_emoji_{name};")

    OUT_C.write_text("\n".join(c_parts), encoding="utf-8")
    OUT_H.write_text("\n".join(h_parts) + "\n", encoding="utf-8")
    print(f"Wrote {OUT_C.name} and {OUT_H.name} ({len(EMOJIS)} emojis)")


if __name__ == "__main__":
    main()
