#!/usr/bin/env python3
"""Generate one style icon per comment bubble (shown centered above the card).

  pip install Pillow
  python tools/gen_comment_bubble_deco.py

Place source PNGs in data/comment_deco/:
  style_dialogue.png, style_festive.png, style_love.png, style_warning.png
"""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC_DIR = ROOT / "data" / "comment_deco"
OUT_C = ROOT / "src" / "comment_bubble_deco_images.c"
OUT_H = ROOT / "include" / "comment_bubble_deco_images.h"

ICON_SIZE = 40
LOVE_W = 56
LOVE_H = 40
CHROMA = 0x07E0
ALPHA_THRESH = 200
WHITE_THRESH = 248

SQUARE_STYLES = ("dialogue", "festive", "warning")


def rgb565(r: int, g: int, b: int) -> int:
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def png_to_rgb565_buf(path: Path, width: int, height: int) -> list[int]:
    from PIL import Image

    im = Image.open(path).convert("RGBA")
    px = im.load()
    bbox = None
    for y in range(im.height):
        for x in range(im.width):
            r, g, b, a = px[x, y]
            if a < 32:
                continue
            if r >= WHITE_THRESH and g >= WHITE_THRESH and b >= WHITE_THRESH:
                continue
            if bbox is None:
                bbox = [x, y, x, y]
            else:
                bbox[0] = min(bbox[0], x)
                bbox[1] = min(bbox[1], y)
                bbox[2] = max(bbox[2], x)
                bbox[3] = max(bbox[3], y)
    if bbox:
        pad = 2
        bbox[0] = max(0, bbox[0] - pad)
        bbox[1] = max(0, bbox[1] - pad)
        bbox[2] = min(im.width - 1, bbox[2] + pad)
        bbox[3] = min(im.height - 1, bbox[3] + pad)
        im = im.crop(tuple(bbox))

    im = im.resize((width, height), Image.Resampling.NEAREST)
    buf: list[int] = []
    px = im.load()
    for y in range(height):
        for x in range(width):
            r, g, b, a = px[x, y]
            if a < ALPHA_THRESH or (
                r >= WHITE_THRESH and g >= WHITE_THRESH and b >= WHITE_THRESH
            ):
                buf.append(CHROMA)
            else:
                buf.append(rgb565(r, g, b))
    return buf


def c_array(name: str, buf: list[int], width: int, height: int) -> str:
    lines = [f"static const uint8_t comment_style_icon_{name}_map[] = {{"]
    for y in range(height):
        row = buf[y * width : (y + 1) * width]
        bytes_out: list[str] = []
        for pixel in row:
            bytes_out.append(f"0x{pixel & 0xFF:02X}")
            bytes_out.append(f"0x{(pixel >> 8) & 0xFF:02X}")
        lines.append("    " + ", ".join(bytes_out) + ",")
    lines.append("};")
    return "\n".join(lines)


def emit_dsc(name: str, width: int, height: int) -> str:
    return f"""
const lv_img_dsc_t comment_style_icon_{name} = {{
    .header.cf = LV_IMG_CF_TRUE_COLOR_CHROMA_KEYED,
    .header.always_zero = 0,
    .header.reserved = 0,
    .header.w = {width},
    .header.h = {height},
    .data_size = sizeof(comment_style_icon_{name}_map),
    .data = comment_style_icon_{name}_map,
}};
"""


def resolve_png(style: str) -> Path:
    primary = SRC_DIR / f"style_{style}.png"
    if primary.is_file():
        return primary
    if style == "love":
        alt = SRC_DIR / "love_envelope.png"
        if alt.is_file():
            return alt
    raise SystemExit(f"Missing {primary} (add PNG under data/comment_deco/)")


def main() -> None:
    try:
        from PIL import Image  # noqa: F401
    except ImportError as exc:
        raise SystemExit("pip install Pillow") from exc

    SRC_DIR.mkdir(parents=True, exist_ok=True)
    # (name, buf, w, h)
    assets: list[tuple[str, list[int], int, int]] = []

    for style in SQUARE_STYLES:
        buf = png_to_rgb565_buf(resolve_png(style), ICON_SIZE, ICON_SIZE)
        assets.append((style, buf, ICON_SIZE, ICON_SIZE))

    love_buf = png_to_rgb565_buf(resolve_png("love"), LOVE_W, LOVE_H)
    assets.append(("love", love_buf, LOVE_W, LOVE_H))

    c_parts = [
        "// Auto-generated by tools/gen_comment_bubble_deco.py",
        "#include <lvgl.h>",
        "",
    ]
    h_parts = [
        "// Auto-generated by tools/gen_comment_bubble_deco.py",
        "#pragma once",
        "#include <lvgl.h>",
        "",
        f"#define COMMENT_STYLE_ICON_SIZE {ICON_SIZE}",
        f"#define COMMENT_STYLE_ICON_LOVE_W {LOVE_W}",
        f"#define COMMENT_STYLE_ICON_LOVE_H {LOVE_H}",
        "",
    ]

    for name, buf, w, h in assets:
        c_parts.append(c_array(name, buf, w, h))
        c_parts.append(emit_dsc(name, w, h))
        h_parts.append(f"extern const lv_img_dsc_t comment_style_icon_{name};")

    OUT_C.write_text("\n".join(c_parts), encoding="utf-8")
    OUT_H.write_text("\n".join(h_parts) + "\n", encoding="utf-8")
    print(f"Wrote {OUT_C.name}, {OUT_H.name} ({len(assets)} icons)")


if __name__ == "__main__":
    main()
