#!/usr/bin/env python3
"""Download Google Weather Icons v4 PNGs and emit LVGL RGB565 C sources.

Icons from https://github.com/mbatthew/GoogleWeatherIconsV4Pack (see repo LICENSE).
Run: pip install Pillow && python tools/gen_google_weather_icons.py
"""

from __future__ import annotations

import struct
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT_C = ROOT / "src" / "weather_icon_images.c"
OUT_H = ROOT / "include" / "weather_icon_images.h"
CACHE = ROOT / "data" / "weather_icons"
BASE_URL = (
    "https://raw.githubusercontent.com/mbatthew/GoogleWeatherIconsV4Pack/main/"
    "app/src/main/res/drawable"
)

ICON_NAMES = [
    "clear_day",
    "clear_night",
    "partly_cloudy_day",
    "partly_cloudy_night",
    "cloudy_day",
    "cloudy_night",
    "rain_day",
    "rain_night",
    "snow_day",
    "snow_night",
    "sleet_day",
    "sleet_night",
    "hail_day",
    "hail_night",
    "thunder_day",
    "thunder_night",
    "thunderstorm_day",
    "thunderstorm_night",
    "fog_day",
    "fog_night",
    "haze_day",
    "haze_night",
    "wind_day",
    "wind_night",
]

SIZE = 72
CHROMA = 0x07E0
ALPHA_THRESH = 128


def rgb565(r: int, g: int, b: int) -> int:
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def download_png(name: str) -> Path:
    CACHE.mkdir(parents=True, exist_ok=True)
    path = CACHE / f"weather_{name}.png"
    if not path.is_file():
        url = f"{BASE_URL}/weather_{name}.png"
        print(f"  download {url}")
        urllib.request.urlretrieve(url, path)
    return path


def png_to_rgb565_buf(path: Path) -> list[int]:
    try:
        from PIL import Image
    except ImportError as exc:
        raise SystemExit("pip install Pillow") from exc

    im = Image.open(path).convert("RGBA")
    im = im.resize((SIZE, SIZE), Image.Resampling.LANCZOS)
    buf: list[int] = []
    for y in range(SIZE):
        for x in range(SIZE):
            r, g, b, a = im.getpixel((x, y))
            if a < ALPHA_THRESH:
                buf.append(CHROMA)
            else:
                buf.append(rgb565(r, g, b))
    return buf


def c_array(name: str, buf: list[int]) -> str:
    lines = [f"static const uint8_t weather_img_{name}_map[] = {{"]
    for y in range(SIZE):
        row = buf[y * SIZE : (y + 1) * SIZE]
        bytes_out: list[str] = []
        for pixel in row:
            bytes_out.append(f"0x{pixel & 0xFF:02X}")
            bytes_out.append(f"0x{(pixel >> 8) & 0xFF:02X}")
        lines.append("    " + ", ".join(bytes_out) + ",")
    lines.append("};")
    return "\n".join(lines)


def main() -> None:
    print(f"Generating {SIZE}x{SIZE} icons from GoogleWeatherIconsV4Pack...")
    c_parts = [
        "// Auto-generated by tools/gen_google_weather_icons.py",
        "// Source: https://github.com/mbatthew/GoogleWeatherIconsV4Pack",
        "#include <lvgl.h>",
        "",
    ]
    h_parts = [
        "// Auto-generated by tools/gen_google_weather_icons.py",
        "#pragma once",
        "#include <lvgl.h>",
        "",
        f"#define WEATHER_ICON_SIZE {SIZE}",
        "",
    ]

    for name in ICON_NAMES:
        path = download_png(name)
        buf = png_to_rgb565_buf(path)
        c_parts.append(c_array(name, buf))
        c_parts.append(
            f"""
const lv_img_dsc_t weather_img_{name} = {{
    .header.cf = LV_IMG_CF_TRUE_COLOR_CHROMA_KEYED,
    .header.always_zero = 0,
    .header.reserved = 0,
    .header.w = {SIZE},
    .header.h = {SIZE},
    .data_size = sizeof(weather_img_{name}_map),
    .data = weather_img_{name}_map,
}};
"""
        )
        h_parts.append(f"extern const lv_img_dsc_t weather_img_{name};")

    h_parts.append("extern const lv_img_dsc_t weather_img_unknown;")
    c_parts.append(
        f"""
/* Fallback: same as cloudy_day */
const lv_img_dsc_t weather_img_unknown = {{
    .header.cf = LV_IMG_CF_TRUE_COLOR_CHROMA_KEYED,
    .header.always_zero = 0,
    .header.reserved = 0,
    .header.w = {SIZE},
    .header.h = {SIZE},
    .data_size = sizeof(weather_img_cloudy_day_map),
    .data = weather_img_cloudy_day_map,
}};
"""
    )

    OUT_C.write_text("\n".join(c_parts), encoding="utf-8")
    OUT_H.write_text("\n".join(h_parts) + "\n", encoding="utf-8")
    print(f"Wrote {OUT_C} and {OUT_H} ({len(ICON_NAMES)} icons)")


if __name__ == "__main__":
    main()
